### ISSUE TITLE
Document get_outliers()

### ISSUE THREAD

**Issue by ianhandel** [CharlotteWoolley/growth_cleanR#9]
In growth_cleanR/data_cleaning_methods/NLME.R document get_outliers() briefly to explain what it returns and why. It's used a lot but it's not obvious what it does. Just a line or so of comment at the function definition. And perhaps a line above the block of get_outlier() calls in other scripts to save hunting for explanations.

**Comment by CharlotteWoolley** [comment]
Code comments have now been added to document the use of get_outliers where appropriate
